services:
  backend:
    image: ghcr.io/akito-0520/muselog:latest
    container_name: muselog-backend
    ports:
      - "80:8080"
    restart: always
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: muselog-frontend
    ports:
      - "3000:3000"
    restart: always
    profiles:
      - development
