
  create table "public"."actresses" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "image_url" text not null,
    "fanza_url" text not null,
    "bust" smallint,
    "waist" smallint,
    "hip" smallint,
    "height" smallint,
    "cup" text not null default 'D'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."actresses" enable row level security;

CREATE UNIQUE INDEX actresses_pkey ON public.actresses USING btree (id);

alter table "public"."actresses" add constraint "actresses_pkey" PRIMARY KEY using index "actresses_pkey";

grant delete on table "public"."actresses" to "anon";

grant insert on table "public"."actresses" to "anon";

grant references on table "public"."actresses" to "anon";

grant select on table "public"."actresses" to "anon";

grant trigger on table "public"."actresses" to "anon";

grant truncate on table "public"."actresses" to "anon";

grant update on table "public"."actresses" to "anon";

grant delete on table "public"."actresses" to "authenticated";

grant insert on table "public"."actresses" to "authenticated";

grant references on table "public"."actresses" to "authenticated";

grant select on table "public"."actresses" to "authenticated";

grant trigger on table "public"."actresses" to "authenticated";

grant truncate on table "public"."actresses" to "authenticated";

grant update on table "public"."actresses" to "authenticated";

grant delete on table "public"."actresses" to "service_role";

grant insert on table "public"."actresses" to "service_role";

grant references on table "public"."actresses" to "service_role";

grant select on table "public"."actresses" to "service_role";

grant trigger on table "public"."actresses" to "service_role";

grant truncate on table "public"."actresses" to "service_role";

grant update on table "public"."actresses" to "service_role";


